version: '3.9'

services:
  db:
    container_name: vk_postgresql
    image: postgres:15.3-alpine3.18
    restart: always
    hostname: postgresql
    env_file: ../.env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: pg_isready -U ${DB_USERNAME} -d ${DB_NAME}
      interval: 2s
      timeout: 3s
      retries: 40
    networks:
      - backend

  # backend:
  #   build: ../.
  #   container_name: vk_app
  #   restart: always
  #   # image: ridpfrep/fb_project:latest
  #   volumes:
  #     - logs_volume:/app/logs
  #   ports:
  #     - "5000:7070"
  #   env_file: ../.env
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #   depends_on:
  #     - db
  #   networks:
  #     - backend
  #   command: ["sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 7070"]

volumes:
  vk_pgdata:

networks:
  backend:
    name: backend
    